name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run link format check
        run: |
          chmod +x scripts/link-format-chk.sh
          chmod +x scripts/buildtable.pl
          scripts/link-format-chk.sh

      - name: Build table
        run: scripts/buildtable.pl > /tmp/table.mediawiki || exit 1

      - name: Check differences
        run: diff README.mediawiki /tmp/table.mediawiki | grep '^[<>] |' > /tmp/after.diff || true

      - name: Compare with previous commit
        run: |
          if git checkout HEAD^ && scripts/buildtable.pl > /tmp/table.mediawiki 2>/dev/null; then
            diff README.mediawiki /tmp/table.mediawiki | grep '^[<>] |' > /tmp/before.diff || true
            newdiff=$(diff -s /tmp/before.diff /tmp/after.diff -u | grep '^+')
            if [ -n "$newdiff" ]; then
              echo "$newdiff"
              exit 1
            fi
          else
            echo 'Cannot build previous commit table for comparison'
          fi
